Try using sample XML from MS docs:
http://learn.iis.net/page.aspx/1082/web-deploy-parameterization#Manifest.xml

Was getting:

[15:21:366]Performing synchronization pass #1.
[15:21:520]Adding MSDeploy.contentPath (MSDeploy.contentPath).
	Details:
	operationType: Add
	providerName: MSDeploy.contentPath
	path: MSDeploy.contentPath
[15:21:538]Adding contentPath (.).
	Details:
	operationType: Add
	providerName: contentPath
	path: .
EXCEPTION: Microsoft.Web.Deployment.DeploymentDetailedException: Site '.' does not exist.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_SITE_DOES_NOT_EXIST.
   at Microsoft.Web.Deployment.AppHostHelper.GetSiteFromAdminManager(IAppHostAdminManager manager, String siteName)
   at Microsoft.Web.Deployment.AppHostHelper.GetIIS7PhysicalPath(IAppHostAdminManager manager, String siteName, String virtualPath)
   at Microsoft.Web.Deployment.IISPathHelper.GetIIS7PhysicalPath(String siteName, String virtualPath, DeploymentBaseContext baseContext)
   at Microsoft.Web.Deployment.IISPathHelper.GetAbsolutePhysicalPath(String inputPath, DeploymentBaseContext baseContext)
   at Microsoft.Web.Deployment.VirtualPathProviderBase.GetPhysicalPath()
   at Microsoft.Web.Deployment.ContentPathProvider.Add(DeploymentObject source, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.Add(DeploymentObject source, DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAdd(DeploymentObject destObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(String provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentWellKnownProvider provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at Microsoft.Web.PlatformInstaller.MSDeployProxy.Install(InstallerContext context, RemoteCredentials remoteCredentials)