Have to intercept at a higher level because at that level `run()` takes no args:
Traceback (most recent call last):
  File "...", line 277, in <module>
    execfile(__file__)
  File "test.cgi", line 19, in <module>
    IISWSGIServer(myapp).run()
TypeError: run() takes at least 2 arguments (1 given)